const events=[
{id:1,name:'Rheinhafen Open Air',type:'Festival',genre:'Techno',date:'2026-09-12',time:'14:00',place:'Karlsruhe Rheinhafen',km:5,price:29,outdoor:true,age:18,x:34,y:61,icon:'⚡'},
{id:2,name:'Street Food Fiesta',type:'Food',genre:'',date:'2026-09-13',time:'11:00',place:'Schlossplatz Karlsruhe',km:1,price:0,outdoor:true,age:0,x:52,y:42,icon:'🍔'},
{id:3,name:'Indie Night',type:'Konzert',genre:'Indie',date:'2026-09-18',time:'20:00',place:'Substage Karlsruhe',km:4,price:22,outdoor:false,age:16,x:67,y:31,icon:'🎸'},
{id:4,name:'City Beats',type:'Club / Party',genre:'House',date:'2026-09-11',time:'23:00',place:'Karlsruhe Innenstadt',km:2,price:14,outdoor:false,age:18,x:57,y:56,icon:'🎧'},
{id:5,name:'Comedy am Abend',type:'Comedy',genre:'',date:'2026-09-20',time:'19:30',place:'Tollhaus Karlsruhe',km:3,price:31,outdoor:false,age:0,x:73,y:67,icon:'🎭'},
{id:6,name:'Durlacher Weinfest',type:'Stadtfest',genre:'Live Music',date:'2026-09-26',time:'12:00',place:'Durlach',km:7,price:0,outdoor:true,age:0,x:83,y:48,icon:'🎉'},
{id:7,name:'Electronic Forest',type:'Festival',genre:'Electronic',date:'2026-10-03',time:'15:00',place:'Ettlingen',km:10,price:39,outdoor:true,age:18,x:46,y:80,icon:'🌲'},
{id:8,name:'Jazz im Hof',type:'Konzert',genre:'Jazz',date:'2026-09-17',time:'19:00',place:'Karlsruhe',km:2,price:18,outdoor:true,age:0,x:43,y:35,icon:'🎷'}];
const $=id=>document.getElementById(id), types=[...new Set(events.map(e=>e.type))],genres=[...new Set(events.map(e=>e.genre).filter(Boolean))];types.forEach(v=>$('type').add(new Option(v,v)));genres.forEach(v=>$('genre').add(new Option(v,v)));const today='2026-09-08';$('from').value=today;
function filtered(){return events.filter(e=>(!$('type').value||e.type===$('type').value)&&(!$('genre').value||e.genre===$('genre').value)&&e.km<=+$('radius').value&&(!$('from').value||e.date>=$('from').value)&&(!$('to').value||e.date<=$('to').value)&&(!$('free').checked||e.price===0)&&(!$('outdoor').checked||e.outdoor)&&(!$('indoor').checked||!e.outdoor)&&(!$('maxPrice').value||e.price<=+$('maxPrice').value)&&(!$('startTime').value||e.time>=$('startTime').value));}
function meta(e){return `<div class='meta'><span class='pill'>📅 ${new Date(e.date+'T12:00').toLocaleDateString('de-DE',{day:'2-digit',month:'short'})} · ${e.time}</span><span class='pill'>📍 ${e.km} km</span><span class='pill'>${e.price?e.price+' €':'Kostenlos'}</span><span class='pill'>${e.outdoor?'☀️ Outdoor':'🏠 Indoor'}</span></div>`}
function content(e,detail=false){return `<div class='eventImage'>${e.icon} ${e.type}</div><h2>${e.name}</h2>${meta(e)}<p>${e.place}</p><div class='meta'><span>${e.genre||e.type}</span>${e.age?`<span>· ab ${e.age}</span>`:''}</div>${detail?`<p>Entdecke ${e.name} in ${e.place}. Dies sind Demo-Daten für den NXTUP-Prototyp. Später werden Beschreibung, Veranstalter und aktuelle Quellen automatisch ergänzt.</p><a class='cta' href='https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.place)}' target='_blank'>ROUTE STARTEN</a><div class='links'><a href='#' onclick='return false'>🎟 Tickets</a><a href='#' onclick='return false'>◎ Instagram</a><a href='#' onclick='return false'>🌐 Website</a></div><small>Quellen: Demo · Veranstalter · Ticketshop</small>`:`<button class='cta' onclick='openEvent(${e.id})'>Event ansehen →</button>`}`}
function render(){const es=filtered();$('count').textContent=`${es.length} Event${es.length===1?'':'s'}`;if($('heroCount'))$('heroCount').textContent=es.length;$('context').textContent=` rund um ${$('place').value||'Karlsruhe'}`;$('pins').innerHTML=es.map(e=>`<button class='pin' style='left:${e.x}%;top:${e.y}%' title='${e.name}' onclick='preview(${e.id})'>${e.icon}</button>`).join('');$('listView').innerHTML=es.map(e=>`<article class='card'>${content(e)}</article>`).join('')||'<p>Keine Events für diese Filter gefunden.</p>'}
window.preview=id=>{$('preview').classList.remove('empty');$('preview').innerHTML=content(events.find(e=>e.id===id))};window.openEvent=id=>{$('modalBody').innerHTML=`<div class='modalContent'>${content(events.find(e=>e.id===id),true)}</div>`;$('modal').showModal()};
['type','genre','radius','from','to','free','outdoor','indoor','maxPrice','startTime','place'].forEach(id=>$(id).addEventListener('input',render));$('more').onclick=()=>$('morePanel').classList.toggle('hidden');$('mapBtn').onclick=()=>{$('mapView').classList.remove('hidden');$('listView').classList.add('hidden');$('mapBtn').classList.add('active');$('listBtn').classList.remove('active')};$('listBtn').onclick=()=>{$('listView').classList.remove('hidden');$('mapView').classList.add('hidden');$('listBtn').classList.add('active');$('mapBtn').classList.remove('active')};$('theme').onclick=()=>document.body.classList.toggle('dark');$('closeModal').onclick=()=>$('modal').close();$('reset').onclick=()=>{['type','genre','to','maxPrice','startTime'].forEach(id=>$(id).value='');['free','outdoor','indoor'].forEach(id=>$(id).checked=false);$('radius').value='50';$('from').value=today;render()};$('now').onclick=()=>{$('from').value=today;$('to').value=today;$('radius').value='20';render()};document.querySelector('[data-quick=today]').onclick=()=>{$('from').value=today;$('to').value=today;render()};document.querySelector('[data-quick=weekend]').onclick=()=>{$('from').value='2026-09-11';$('to').value='2026-09-13';render()};$('locate').onclick=()=>{if(navigator.geolocation)navigator.geolocation.getCurrentPosition(()=>{alert('Standort erkannt. In der finalen Version wird die Karte darauf zentriert.')},()=>alert('Standort konnte nicht abgerufen werden.'))};function soon(t){$('modalBody').innerHTML=`<div class='modalContent'><h1>${t}</h1><p>Diese Funktion ist für die nächste Ausbaustufe vorgesehen. Der Prototyp funktioniert bewusst ohne Datenbank und Benutzerkonto.</p></div>`;$('modal').showModal()}$('saved').onclick=()=>soon('Merkliste – bald verfügbar');$('profile').onclick=()=>soon('NXTUP Account – bald verfügbar');$('navSearch').onclick=()=>document.querySelector('.discoveryShell').scrollIntoView({behavior:'smooth'});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
