'use strict';
const $=id=>document.getElementById(id);
const TODAY=new Date(); const DAY=86400000;
const iso=d=>new Date(d).toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const addDays=n=>iso(TODAY.getTime()+n*DAY);
const nowSlot=h=>{const d=new Date(Date.now()+h*3600000);return {date:iso(d),time:d.toTimeString().slice(0,5)}};
const hash=s=>[...String(s)].reduce((a,c)=>((a*33)^c.charCodeAt(0))>>>0,5381);

const citySeed=[
['Karlsruhe','Deutschland',49.0069,8.4037],['Stuttgart','Deutschland',48.7758,9.1829],['Heidelberg','Deutschland',49.3988,8.6724],['Freiburg','Deutschland',47.999,7.8421],['Mannheim','Deutschland',49.4875,8.466],['Berlin','Deutschland',52.52,13.405],['Hamburg','Deutschland',53.5511,9.9937],['München','Deutschland',48.1351,11.582],['Köln','Deutschland',50.9375,6.9603],['Frankfurt','Deutschland',50.1109,8.6821],['Leipzig','Deutschland',51.3397,12.3731],['Dresden','Deutschland',51.0504,13.7373],
['Amsterdam','Niederlande',52.3676,4.9041],['Rotterdam','Niederlande',51.9244,4.4777],['Utrecht','Niederlande',52.0907,5.1214],['Paris','Frankreich',48.8566,2.3522],['Lyon','Frankreich',45.764,4.8357],['Marseille','Frankreich',43.2965,5.3698],['Nizza','Frankreich',43.7102,7.262],['Bordeaux','Frankreich',44.8378,-0.5792],['Barcelona','Spanien',41.3874,2.1686],['Madrid','Spanien',40.4168,-3.7038],['Valencia','Spanien',39.4699,-0.3763],['Sevilla','Spanien',37.3891,-5.9845],['Bilbao','Spanien',43.263,-2.935],['Ibiza','Spanien',38.9067,1.4206],
['London','Vereinigtes Königreich',51.5072,-0.1276],['Manchester','Vereinigtes Königreich',53.4808,-2.2426],['Bristol','Vereinigtes Königreich',51.4545,-2.5879],['Edinburgh','Vereinigtes Königreich',55.9533,-3.1883],['Dublin','Irland',53.3498,-6.2603],['Wien','Österreich',48.2082,16.3738],['Salzburg','Österreich',47.8095,13.055],['Graz','Österreich',47.0707,15.4395],['Zürich','Schweiz',47.3769,8.5417],['Basel','Schweiz',47.5596,7.5886],['Genf','Schweiz',46.2044,6.1432],['Bern','Schweiz',46.948,7.4474],
['Prag','Tschechien',50.0755,14.4378],['Brünn','Tschechien',49.1951,16.6068],['Budapest','Ungarn',47.4979,19.0402],['Warschau','Polen',52.2297,21.0122],['Krakau','Polen',50.0647,19.945],['Danzig','Polen',54.352,18.6466],['Kopenhagen','Dänemark',55.6761,12.5683],['Aarhus','Dänemark',56.1629,10.2039],['Stockholm','Schweden',59.3293,18.0686],['Göteborg','Schweden',57.7089,11.9746],['Oslo','Norwegen',59.9139,10.7522],['Bergen','Norwegen',60.3913,5.3221],['Helsinki','Finnland',60.1699,24.9384],['Tallinn','Estland',59.437,24.7536],['Riga','Lettland',56.9496,24.1052],['Vilnius','Litauen',54.6872,25.2797],
['Mailand','Italien',45.4642,9.19],['Rom','Italien',41.9028,12.4964],['Florenz','Italien',43.7696,11.2558],['Neapel','Italien',40.8518,14.2681],['Bologna','Italien',44.4949,11.3426],['Turin','Italien',45.0703,7.6869],['Lissabon','Portugal',38.7223,-9.1393],['Porto','Portugal',41.1579,-8.6291],['Brüssel','Belgien',50.8503,4.3517],['Antwerpen','Belgien',51.2194,4.4025],['Athen','Griechenland',37.9838,23.7275],['Thessaloniki','Griechenland',40.6401,22.9444],['Zagreb','Kroatien',45.815,15.9819],['Split','Kroatien',43.5081,16.4402],['Ljubljana','Slowenien',46.0569,14.5058],['Bratislava','Slowakei',48.1486,17.1077]
].map(x=>({name:x[0],country:x[1],lat:x[2],lng:x[3]}));
const cities=[...citySeed];
const templates=[
['Open Air Sessions','Festival','Electronic',29,true,18],['Street Food Market','Food & Drinks','',0,true,0],['Indie Night','Konzert','Indie',22,false,16],['Night Shift','Party / Club','House',16,false,18],['Comedy Club','Comedy','',31,false,0],['City Festival','Stadtfest','Live Music',0,true,0],['Bass District','Festival','Techno',39,true,18],['Jazz Courtyard','Konzert','Jazz',18,true,0],['Family Sunday','Familie','',8,true,0],['Culture Night','Kultur','',12,false,0],['Warehouse Session','Party / Club','Hardtechno',24,false,18],['Makers Market','Markt','',0,true,0],['Rooftop Day Party','Party / Club','House',20,true,18],['Live Arena','Konzert','Pop',35,false,0]
];
const events=[];let seq=1;
function ensureEvents(city,count=18){if(events.some(e=>e.city===city.name))return;const h=hash(city.name+city.country);for(let i=0;i<count;i++){const t=templates[(h+i)%templates.length];const live=i===0?nowSlot(-1):i===1?nowSlot(1):null;const angle=((h+i*29)%360)*Math.PI/180;const r=.008+((h+i*13)%35)/1000;events.push({id:seq++,name:i===0?`${city.name} Live`:i===1?`${city.name} Next Up`:t[0],type:t[1],genre:t[2],price:t[3],outdoor:t[4],age:t[5],date:live?live.date:addDays((i*3+(h%17))%85+1),time:live?live.time:['10:00','12:30','16:00','18:30','20:00','22:00','23:30'][i%7],city:city.name,country:city.country,place:[`${city.name} Center`,`${city.name} Riverside`,`${city.name} Hall`,`${city.name} Club`,`${city.name} Quarter`][i%5],lat:city.lat+Math.cos(angle)*r,lng:city.lng+Math.sin(angle)*r,popularity:60+((h+i*7)%40),sources:['Veranstalter','Ticketshop',i%2?'Instagram':'Lokaler Eventkalender']})}}
cities.forEach(c=>ensureEvents(c,c.name==='Barcelona'?24:14));
const venues=[{name:'Gotec Club',city:'Karlsruhe',type:'Club'},{name:'Razzmatazz',city:'Barcelona',type:'Club'},{name:'Input',city:'Barcelona',type:'Club'},{name:'Berghain',city:'Berlin',type:'Club'},{name:'Fabric',city:'London',type:'Club'},{name:'Paradiso',city:'Amsterdam',type:'Venue'}];

const state={city:cities[0],cityFilters:new Set(),view:localStorage.getItem('nxtupViewV11')||'map',free:false,outdoor:false,indoor:false,consent:{map:false,personalization:false},map:null,mapReady:false,markers:[],language:'de'};
const favKey='nxtupFavV11',followKey='nxtupFollowV11',themeKey='nxtupThemeV11',consentKey='nxtupConsentV11';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const favs=()=>read(favKey,[]); const followed=()=>read(followKey,[]);

function dateObj(e){return new Date(`${e.date}T${e.time}:00`)}
function isLive(e){const start=dateObj(e), end=new Date(start.getTime()+5*3600000);return Date.now()>=start.getTime()&&Date.now()<=end.getTime()}
function startsSoon(e){const d=(dateObj(e)-Date.now())/3600000;return d>0&&d<=3}
function status(e){if(isLive(e))return 'LIVE';if(startsSoon(e))return 'STARTET BALD';return new Date(e.date+'T12:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'short'})}
function price(e){return e.price?`${e.price} €`:'Kostenlos'}
function weekendRange(){const d=new Date();const day=d.getDay();const untilFri=(5-day+7)%7;const fri=new Date(d.getFullYear(),d.getMonth(),d.getDate()+untilFri);const sun=new Date(fri.getTime()+2*DAY);return [iso(fri),iso(sun)]}
function cityFiltered(e){if(e.city.toLowerCase()!==state.city.name.toLowerCase())return false;const f=state.cityFilters;if(!f.size)return true;if(f.has('today')&&e.date!==iso(TODAY))return false;if(f.has('weekend')){const [a,b]=weekendRange();if(e.date<a||e.date>b)return false}if(f.has('free')&&e.price!==0)return false;if(f.has('nightlife')&&e.type!=='Party / Club')return false;if(f.has('concerts')&&e.type!=='Konzert')return false;if(f.has('festivals')&&e.type!=='Festival')return false;if(f.has('food')&&e.type!=='Food & Drinks')return false;if(f.has('culture')&&e.type!=='Kultur')return false;return true}
function generalFiltered(){const type=$('type').value,genre=$('genre').value,from=$('from').value,to=$('to').value,min=Number($('minPrice').value||0),max=$('maxPrice').value===''?Infinity:Number($('maxPrice').value);return events.filter(e=>e.city===state.city.name&&(!type||e.type===type)&&(!genre||e.genre===genre)&&(e.price>=min&&e.price<=max)&&(!$('from').value||e.date>=from)&&(!to||e.date<=to)&&(!state.free||e.price===0)&&(!state.outdoor||e.outdoor)&&(!state.indoor||!e.outdoor))}
function sorted(es){const s=$('sort').value;return [...es].sort((a,b)=>s==='date'?dateObj(a)-dateObj(b):s==='price'?a.price-b.price:s==='popular'?b.popularity-a.popularity:(Number(isLive(b))-Number(isLive(a)))||b.popularity-a.popularity)}
let currentResults=()=>sorted(generalFiltered());

function card(e,list=false){const saved=favs().includes(e.id);return `<article class="eventCard ${list?'listCard':''}" data-event="${e.id}"><div class="eventImage"><span class="status">${esc(status(e))}</span><span class="eventType">${esc(e.type)}</span><button class="favBtn ${saved?'saved':''}" data-fav="${e.id}" type="button" aria-label="Favorit">${saved?'♥':'♡'}</button></div><div class="cardBody"><h3>${esc(e.name)}</h3><p>${esc(e.place)} · ${esc(e.city)}</p><div class="metaRow"><span>${esc(e.time)} Uhr</span><span>${esc(price(e))}</span>${e.genre?`<span>${esc(e.genre)}</span>`:''}</div></div></article>`}
function empty(){return `<div class="emptyPreview"><strong>Keine passenden Events</strong><p>Filter zurücksetzen oder einen größeren Zeitraum wählen.</p></div>`}
function render(es=currentResults()){currentResults=()=>sorted(es.filter(e=>e.city===state.city.name));const out=sorted(es);$('count').textContent=`${out.length} Event${out.length===1?'':'s'}`;$('context').textContent=` in ${state.city.name}`;$('gridView').innerHTML=out.length?out.map(e=>card(e)).join(''):empty();$('listView').innerHTML=out.length?out.map(e=>card(e,true)).join(''):empty();bindCards();renderInspiration(out);if(state.mapReady)renderMarkers(out)}
function bindCards(){document.querySelectorAll('[data-event]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-fav]'))return;openEvent(Number(el.dataset.event))});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(Number(b.dataset.fav))})}
function toggleFav(id){showPremium('Favoriten gehören zu NXTUP+. Speichere Events, Locations und Suchen in deinem Premium-Profil.')}
function renderInspiration(es){const src=es.length?es:events.filter(e=>e.city===state.city.name);$('inspirationRail').innerHTML=src.slice(0,3).map(e=>`<button class="miniInspire" data-inspire="${e.id}" type="button"><h3>${esc(e.name)}</h3><p>${esc(e.city)} · ${esc(price(e))}</p></button>`).join('');document.querySelectorAll('[data-inspire]').forEach(b=>b.onclick=()=>openEvent(Number(b.dataset.inspire)))}
function detail(e){return `<div class="modalInner"><div class="modalHero"><span class="status">${esc(status(e))}</span></div><h1>${esc(e.name)}</h1><p>${esc(e.place)} · ${esc(e.city)}, ${esc(e.country)}</p><div class="detailMeta"><span>${esc(new Date(e.date+'T12:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}))}</span><span>${esc(e.time)} Uhr</span><span>${esc(price(e))}</span><span>${esc(e.genre||e.type)}</span></div><div class="detailActions"><a class="primaryAction" href="#" onclick="return false">Tickets & Infos</a><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.lat+','+e.lng)}">Route</a><button type="button" data-share="${e.id}">Teilen</button></div><h3>Über das Event</h3><p>NXTUP bündelt verfügbare Eventinformationen und führt mehrere Quellen zu einem Eintrag zusammen. In dieser Prototyp-Version sind Eventdaten teilweise Demo-Daten.</p><h3>Quellen</h3><p>${e.sources.map(esc).join(' · ')}</p></div>`}
function openEvent(id){const e=events.find(x=>x.id===id);if(!e)return;if(innerWidth>900){$('eventDrawerBody').innerHTML=detail(e);$('eventDrawer').classList.remove('hidden');const sh=$('eventDrawerBody').querySelector('[data-share]');if(sh)sh.onclick=()=>shareEvent(e);return}$('eventModalBody').innerHTML=detail(e);$('eventModal').showModal();const sh=$('eventModalBody').querySelector('[data-share]');if(sh)sh.onclick=()=>shareEvent(e)}
function showPreview(e){if(innerWidth>900){openEvent(e.id);return}$('preview').classList.remove('empty');$('preview').innerHTML=`<button class="previewClose" type="button">×</button>${card(e)}<div class="modalInner" style="padding-top:4px"><button class="primaryBtn" id="previewDetails" type="button">Eventdetails öffnen</button></div>`;$('preview').querySelector('.previewClose').onclick=closePreview;$('preview').querySelector('[data-event]').onclick=()=>{};$('preview').querySelector('[data-fav]').onclick=ev=>{ev.stopPropagation();toggleFav(e.id)};$('previewDetails').onclick=()=>{$('eventModalBody').innerHTML=detail(e);$('eventModal').showModal()}}
function closePreview(){$('preview').classList.add('empty');$('preview').innerHTML='<div class="emptyPreview"><strong>Event auswählen</strong><p>Klicke auf einen Pin oder ein Event.</p></div>'}
async function shareEvent(e){if(navigator.share)await navigator.share({title:e.name,text:`${e.name} in ${e.city}`,url:location.href});else navigator.clipboard?.writeText(location.href)}

function setCity(city){state.city={...city};state.cityFilters.clear();ensureEvents(state.city,18);$('citySearch').value=city.name;$('place').value=city.name;$('cityModeTitle').textContent=city.name;$('cityModeSubtitle').textContent=`Alle Events in ${city.name} entdecken.`;document.querySelectorAll('.cityFilter').forEach(b=>b.classList.remove('active'));render(events.filter(e=>e.city===city.name));if(state.mapReady)centerMap()}
async function findCity(q){const needle=q.trim().toLowerCase();let city=cities.find(c=>c.name.toLowerCase()===needle)||cities.find(c=>c.name.toLowerCase().startsWith(needle));if(city)return city;if(!state.consent.map){showGeneric('Europaweite Ortssuche','Für Orte außerhalb der eingebauten Demo-Städte aktiviere bitte die externe Karte/Ortssuche über die Cookie-Einstellungen.');return null}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&addressdetails=1&q=${encodeURIComponent(q+' Europe')}`,{headers:{'Accept-Language':'de'}});const d=await r.json();if(!d.length)throw 0;city={name:d[0].display_name.split(',')[0],country:d[0].address?.country||'',lat:+d[0].lat,lng:+d[0].lon};cities.push(city);ensureEvents(city,18);return city}catch{showGeneric('Ort nicht gefunden','Bitte prüfe die Schreibweise oder suche nach Stadt + Land.');return null}}
async function citySearch(){const c=await findCity($('citySearch').value);if(c){setCity(c);$('resultsTop').scrollIntoView({behavior:'smooth',block:'start'})}}
function applyCityFilters(){const es=events.filter(cityFiltered);currentResults=()=>sorted(es);render(es);setView(state.view);$('resultsTop').scrollIntoView({behavior:'smooth',block:'start'})}
function resetCityFilters(){state.cityFilters.clear();document.querySelectorAll('.cityFilter').forEach(b=>b.classList.remove('active'));applyCityFilters()}

function fillSelects(){const types=[...new Set(templates.map(t=>t[1]))].sort(),genres=[...new Set(templates.map(t=>t[2]).filter(Boolean))].sort();$('type').innerHTML='<option value="">Alle</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');$('genre').innerHTML='<option value="">Alle</option>'+genres.map(x=>`<option>${esc(x)}</option>`).join('')}
function resetGeneral(){['type','genre','maxPrice'].forEach(id=>$(id).value='');$('minPrice').value='0';$('from').value=iso(TODAY);$('to').value='';state.free=state.outdoor=state.indoor=false;['freeBtn','outdoorBtn','indoorBtn'].forEach(id=>$(id).classList.remove('active'));render(events.filter(e=>e.city===state.city.name))}
function setView(v){if(v==='split')v='map';state.view=v;localStorage.setItem('nxtupViewV11',v);['map','grid','list'].forEach(x=>{$(`${x}View`).classList.toggle('hidden',x!==v);$(`${x}Btn`).classList.toggle('active',x===v)});$('splitBtn')?.classList.toggle('active',false);if(v==='map'){enableMapIfAllowed();setTimeout(()=>state.map?.invalidateSize(),100)} }

function initConsent(){const c=read(consentKey,null);if(c){state.consent={...state.consent,...c};return}$('consentBanner').classList.remove('hidden')}
function showConsent(){$('consentBanner').classList.remove('hidden')}
function saveConsent(map,personalization){state.consent={map,personalization};write(consentKey,state.consent);$('consentBanner').classList.add('hidden');if(map&&state.view==='map')enableMapIfAllowed()}
async function enableMapIfAllowed(){if(!state.consent.map){$('mapFallback').classList.remove('hidden');return}if(state.mapReady)return;if(!window.L){await loadLeaflet()}state.map=L.map('map',{zoomControl:false}).setView([state.city.lat,state.city.lng],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map);state.mapReady=true;$('mapFallback').classList.add('hidden');renderMarkers(currentResults())}
function loadLeaflet(){return new Promise((resolve,reject)=>{const l=document.createElement('link');l.rel='stylesheet';l.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(l);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function renderMarkers(es){if(!state.mapReady)return;state.markers.forEach(m=>m.remove());state.markers=[];es.forEach(e=>{const m=L.marker([e.lat,e.lng]).addTo(state.map).bindTooltip(e.name);m.on('click',()=>showPreview(e));state.markers.push(m)});if(es.length){const group=L.featureGroup(state.markers);state.map.fitBounds(group.getBounds().pad(.18),{maxZoom:14})}else centerMap()}
function centerMap(){state.map?.setView([state.city.lat,state.city.lng],12)}

function searchGlobal(q){q=q.trim();if(!q)return;const venue=venues.find(v=>v.name.toLowerCase().includes(q.toLowerCase()));if(venue){showVenue(venue);return}const city=cities.find(c=>c.name.toLowerCase().includes(q.toLowerCase()));if(city){setCity(city);$('cityMode').scrollIntoView({behavior:'smooth'});return}const hits=events.filter(e=>e.name.toLowerCase().includes(q.toLowerCase())||e.genre.toLowerCase().includes(q.toLowerCase())||e.type.toLowerCase().includes(q.toLowerCase()));if(hits.length){const target=hits[0].city;const c=cities.find(x=>x.name===target);if(c)state.city=c;setView('grid');render(hits);$('resultsTop').scrollIntoView({behavior:'smooth'});return}findCity(q).then(c=>{if(c){setCity(c);$('resultsTop').scrollIntoView({behavior:'smooth'})}})}
function showVenue(v){const isFollow=followed().includes(v.name);const es=events.filter(e=>e.city===v.city&&(v.type==='Club'?e.type==='Party / Club':true));$('genericModalBody').innerHTML=`<div class="modalInner"><p class="kicker">LOCATION</p><h1>${esc(v.name)}</h1><p>${esc(v.city)} · ${esc(v.type)}</p><button id="followVenueBtn" class="primaryBtn" type="button">${isFollow?'Gefolgt':'Location folgen'}</button><h3>Kommende Events</h3>${es.slice(0,6).map(e=>`<button class="miniInspire" data-venue-event="${e.id}" type="button"><h3>${esc(e.name)}</h3><p>${esc(e.date)} · ${esc(e.time)} · ${esc(price(e))}</p></button>`).join('')}</div>`;$('genericModal').showModal();$('followVenueBtn').onclick=()=>showPremium('Locations folgen gehört zu NXTUP+. Erhalte neue Events deiner Lieblingslocations direkt in NXTUP.');document.querySelectorAll('[data-venue-event]').forEach(b=>b.onclick=()=>openEvent(Number(b.dataset.venueEvent)))}
function showGeneric(title,text){$('genericModalBody').innerHTML=`<div class="modalInner"><p class="kicker">NXTUP</p><h1>${esc(title)}</h1><p>${text}</p></div>`;$('genericModal').showModal()}
function showPremium(reason='Plan my Weekend, dein nächster Move, Favoriten, Locations folgen und persönliche Empfehlungen.'){$('genericModalBody').innerHTML=`<div class="modalInner"><p class="kicker">NXTUP+</p><h1>Dein Europa. Deine Events.</h1><p>${reason}</p><div class="priceChoice"><button class="priceCard" data-plan="month" type="button"><strong>1,99 €</strong><span>pro Monat</span></button><button class="priceCard best" data-plan="year" type="button"><b>Bester Preis</b><strong>14,99 €</strong><span>pro Jahr</span></button></div><button id="startTrialBtn" class="primaryBtn wide" style="margin-top:18px" type="button">3 Tage kostenlos testen</button><p class="finePrint">Danach läuft das gewählte Abo weiter, sofern es nicht vorher gekündigt wird. Zahlung ist im Prototyp simuliert.</p></div>`;$('genericModal').showModal();document.querySelectorAll('.priceCard').forEach(b=>b.onclick=()=>{document.querySelectorAll('.priceCard').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('genericModalBody').querySelector('[data-plan=year]').classList.add('selected');$('startTrialBtn').onclick=()=>showGeneric('NXTUP+ Demo','Der Upgrade-Flow funktioniert. Für echte Abos wird im Produktionsschritt ein Zahlungsanbieter angebunden.')}
function showAccount(kind){showGeneric(kind==='register'?'Profil erstellen':'Anmelden',kind==='register'?'Das Login-Profil ist kostenlos. Favoriten, Locations folgen, Interessen, Lieblingsstädte, Suchverlauf und gespeicherte Suchen gehören zu NXTUP+.':'Der Login-Flow ist im Prototyp vorbereitet und wird mit dem Backend aktiviert.')}

function theme(){document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');$('themeBtn').textContent=dark?'Hell':'Dunkel';localStorage.setItem(themeKey,dark?'dark':'light')}
function initTheme(){const t=localStorage.getItem(themeKey);if(t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches))document.body.classList.add('dark');$('themeBtn').textContent=document.body.classList.contains('dark')?'Hell':'Dunkel'}

function init(){fillSelects();$('from').value=iso(TODAY);initTheme();initConsent();render(events.filter(e=>e.city===state.city.name));
 document.querySelectorAll('.cityFilter').forEach(b=>b.onclick=()=>{const k=b.dataset.cityfilter;state.cityFilters.has(k)?state.cityFilters.delete(k):state.cityFilters.add(k);b.classList.toggle('active',state.cityFilters.has(k))});
 $('cityShowBtn').onclick=applyCityFilters;$('cityResetBtn').onclick=resetCityFilters;$('citySearchBtn').onclick=citySearch;$('citySearch').onkeydown=e=>{if(e.key==='Enter')citySearch()};$('changeCityBtn').onclick=()=>$('citySearch').focus();
 $('mainSearchBtn').onclick=()=>{state.cityFilters.clear();document.querySelectorAll('.cityFilter').forEach(b=>b.classList.remove('active'));render(generalFiltered());setView(state.view);$('resultsTop').scrollIntoView({behavior:'smooth'})};$('clearFiltersBtn').onclick=resetGeneral;
 [['freeBtn','free'],['outdoorBtn','outdoor'],['indoorBtn','indoor']].forEach(([id,k])=>$(id).onclick=()=>{state[k]=!state[k];$(id).classList.toggle('active',state[k])});
 $('globalSearchForm').onsubmit=e=>{e.preventDefault();searchGlobal($('globalSearch').value)};$('sort').onchange=()=>render(currentResults());$('mapBtn').onclick=()=>setView('map');$('gridBtn').onclick=()=>setView('grid');$('listBtn').onclick=()=>setView('list');$('splitBtn').onclick=()=>setView('map');$('enableMap').onclick=()=>saveConsent(true,state.consent.personalization);$('zoomIn').onclick=()=>state.map?.zoomIn();$('zoomOut').onclick=()=>state.map?.zoomOut();$('mapReset').onclick=centerMap;
 $('themeBtn').onclick=theme;$('languageBtn').onclick=()=>{$('languageBtn').textContent=$('languageBtn').textContent==='DE'?'EN':'DE'};$('loginBtn').onclick=()=>showAccount('login');$('registerBtn').onclick=()=>showAccount('register');$('premiumBtn').onclick=()=>showPremium();$('savedSearchBtn').onclick=()=>showPremium('Gespeicherte Suchen gehören zu NXTUP+. Speichere Orte, Filter und Lieblingssuchen für später.');
 $('discoverBtn').onclick=e=>{e.stopPropagation();$('discover').scrollIntoView({behavior:'smooth'})};$('hero').onclick=e=>{if(e.target.closest('button'))return;$('discover').scrollIntoView({behavior:'smooth'})};$('hero').onkeydown=e=>{if(e.key==='Enter')$('discover').scrollIntoView({behavior:'smooth'})};
 $('nowBtn').onclick=e=>{e.stopPropagation();const es=events.filter(x=>x.city===state.city.name&&(isLive(x)||startsSoon(x)));setView('grid');render(es.length?es:events.filter(x=>x.city===state.city.name).sort((a,b)=>dateObj(a)-dateObj(b)).slice(0,6));$('resultsTop').scrollIntoView({behavior:'smooth'})};
 $('homeBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('mobileSaved').onclick=()=>showPremium('Favoriten gehören zu NXTUP+. Speichere Events und Locations und finde sie jederzeit wieder.');$('mobileProfile').onclick=()=>showAccount('register');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='map'){setView('map');$('resultsTop').scrollIntoView({behavior:'smooth'});return}const t=b.dataset.nav==='home'?'hero':'discover';$(t).scrollIntoView({behavior:'smooth'})});
 $('privacyBtn').onclick=()=>showGeneric('Datenschutz','NXTUP verwendet im Prototyp keine Werbetracker. Externe Karten und lokale Personalisierung werden nur nach deiner Wahl aktiviert. Vor Veröffentlichung müssen Verantwortlicher, Dienstleister und Rechtsgrundlagen ergänzt und rechtlich geprüft werden.');$('cookieBtn').onclick=showConsent;$('organizerBtn').onclick=()=>showGeneric('Für Veranstalter','Events beanspruchen, Locations verwalten und Social-/Eventquellen verbinden ist für die spätere Backend-Version vorgesehen.');
 $('drawerClose').onclick=()=>$('eventDrawer').classList.add('hidden');$('necessaryConsent').onclick=()=>saveConsent(false,false);$('allConsent').onclick=()=>saveConsent(true,true);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('dialog[open]').forEach(d=>d.close());closePreview()}});
 setView(state.view);if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
}
document.addEventListener('DOMContentLoaded',init);
